name: border_beam
description: "A customizable Flutter widget that draws an animated gradient beam around a child widget."
version: 0.0.1
repository:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
